### ISSUE TITLE
Review Content

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#1]
### List of pages (individual pages, guides, etc.):
- [x] https://github.com/freeCodeCamp/contribute/issues/86
- [x] https://github.com/freeCodeCamp/contribute/issues/132
- [x] https://github.com/freeCodeCamp/contribute/issues/133
- [ ] Work on translating resources - [how-to-translate-files.md](https://contribute.freecodecamp.org/#/how-to-translate-files)
- [ ] Work on proofreading translations - [how-to-proofread-files.md](https://contribute.freecodecamp.org/#/how-to-proofread-files)
- [x] Set up freeCodeCamp - [how-to-setup-freecodecamp-locally.md](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally)
- [ ] Follow best-practices - [codebase-best-practices.md](https://contribute.freecodecamp.org/#/codebase-best-practices)
- [ ] Work on Codebase - [how-to-contribute-to-the-codebase.md](https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase)
- [ ] Work on Coding Challenges - [how-to-work-on-coding-challenges.md](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges)
- [ ] Use the Curriculum Helpers - [curriculum-help.md](https://contribute.freecodecamp.org/#/curriculum-help)
- [ ] Work on Component Library - [how-to-work-on-the-component-library.md](https://contribute.freecodecamp.org/#/how-to-work-on-the-component-library)
- [ ] Work on Practice Projects - [how-to-work-on-practice-projects.md](https://contribute.freecodecamp.org/#/how-to-work-on-practice-projects)
- [ ] Work on Mobile app - [how-to-setup-freecodecamp-mobile-app-locally.md](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-mobile-app-locally)
- [ ] Work on tutorials with CodeRoad - [how-to-work-on-tutorials-that-use-coderoad.md](https://contribute.freecodecamp.org/#/how-to-work-on-tutorials-that-use-coderoad)
- [x] https://github.com/freeCodeCamp/contribute/issues/355
- [ ] Work on Playwright Tests - [how-to-add-playwright-tests.md](https://contribute.freecodecamp.org/#/how-to-add-playwright-tests)
- [ ] Work on Video Challenges - [how-to-help-with-video-challenges.md](https://contribute.freecodecamp.org/#/how-to-help-with-video-challenges)
- [x] https://github.com/freeCodeCamp/contribute/issues/350
- [ ] https://github.com/freeCodeCamp/contribute/issues/11
- [ ] Understand the curriculum file structure - [curriculum-file-structure.md](https://contribute.freecodecamp.org/#/curriculum-file-structure)
- [ ] Debug outgoing emails locally - [how-to-catch-outgoing-emails-locally.md](https://contribute.freecodecamp.org/#/how-to-catch-outgoing-emails-locally)
- [ ] Work on Cypress Tests - [how-to-add-cypress-tests.md](https://contribute.freecodecamp.org/#/how-to-add-cypress-tests)
- [ ] Set up freeCodeCamp on Windows (WSL) - [how-to-setup-wsl.md](https://contribute.freecodecamp.org/#/how-to-setup-wsl)
- [ ] Use Docker on Windows Home - [how-to-use-docker-on-windows-home.md](https://contribute.freecodecamp.org/#/how-to-use-docker-on-windows-home)
- [ ] User Token Workflow - [user-token-workflow.md](https://contribute.freecodecamp.org/#/user-token-workflow)
- [ ] Troubleshooting Development Issues - [troubleshooting-development-issues.md](https://contribute.freecodecamp.org/#/troubleshooting-development-issues)
- [ ] Authors Analytics Manual - [authors-analytics-manual.md](https://contribute.freecodecamp.org/#/authors-analytics-manual)
- [ ] Moderator Handbook - [moderator-handbook.md](https://contribute.freecodecamp.org/#/moderator-handbook)
- [ ] Reply Templates - [reply-templates.md](https://contribute.freecodecamp.org/#/reply-templates)
- [ ] Language Lead Handbook - [language-lead-handbook.md](https://contribute.freecodecamp.org/#/language-lead-handbook)
- [x] DevOps Handbook - [devops.md](https://contribute.freecodecamp.org/#/devops)
- [ ] Courses VSCode Extension - [courses-vscode-extension.md](https://contribute.freecodecamp.org/#/courses-vscode-extension)
- [ ] Enable New Language - [how-to-enable-new-languages.md](https://contribute.freecodecamp.org/#/how-to-enable-new-languages)

**Comment by a2937** [comment]
Hi there. I think it would be nice to list the PR scopes on the [pull request page](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request). As far as I am aware, the PR scopes aren't likely to change anytime soon.

**Comment by naomi-lgbt** [comment]
IMHO we'd need to have a discussion on what scopes should be used. I don't believe we've ever actually had a unified definition of scopes.

**Comment by ShaunSHamilton** [comment]
With this move, do we want/hope/plan to move some of our other docs to here as well? Or, keep them external to prevent this repo from becoming _too much_?

E.g. `curriculum-helpers`, `freecodecamp-os`, `courses-vscode-extension`, and possibly boilerplate docs (how to contribute to things like `web3-curriculum`, or `back-end-development-and-apis`)

I mention this, because I plan to make some of the other docs a lot more useful, and do not want to do it if I would need to redo the work here - I doubt it would be copy-pasta.

**Comment by raisedadead** [comment]
Yes - That is fine. The objective of the project is to be one stop shop for all things contributions to freeCodeCamp.

**Comment by CBID2** [comment]
> With this move, do we want/hope/plan to move some of our other docs to here as well? Or, keep them external to prevent this repo from becoming _too much_?
> 
> E.g. `curriculum-helpers`, `freecodecamp-os`, `courses-vscode-extension`, and possibly boilerplate docs (how to contribute to things like `web3-curriculum`, or `back-end-development-and-apis`)
> 
> I mention this, because I plan to make some of the other docs a lot more useful, and do not want to do it if I would need to redo the work here - I doubt it would be copy-pasta.

Speaking of docs, I

**Comment by CBID2** [comment]
> With this move, do we want/hope/plan to move some of our other docs to here as well? Or, keep them external to prevent this repo from becoming _too much_?
> 
> E.g. `curriculum-helpers`, `freecodecamp-os`, `courses-vscode-extension`, and possibly boilerplate docs (how to contribute to things like `web3-curriculum`, or `back-end-development-and-apis`)
> 
> I mention this, because I plan to make some of the other docs a lot more useful, and do not want to do it if I would need to redo the work here - I doubt it would be copy-pasta.

I think the `moderator handbook`and `Language Lead Handbook` files could be in the internal docs section.

**Comment by chinar-amrutkar** [comment]
I can help with reviewing content. Are all of these files still pending?

**Comment by lhamo07** [comment]
Hello, I am new to open source contribution. It would be great help if somebody help me where I can contribute.

**Comment by chandanashetty31** [comment]
“Hi, I’d like to work on this issue. Could you please assign me or guide me for the work?”

**Comment by a2937** [comment]
> “Hi, I’d like to work on this issue. Could you please assign me or guide me for the work?”

We typically do not assign issues. Instead, we accept the first pull request that comprehensively solves the issue.

Issues labeled with `help wanted` or `first timers only` are open for contributions.

Please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/). We prioritize contributors following the instructions in our guide. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing - our community will be happy to assist you.

**Comment by SulthanNK** [comment]
Hello @a2937 & @raisedadead 👋

Need a guidance on what are those scopes we can include on "Open a pull request" page. We have few existing [Scope](https://github.com/freeCodeCamp/freeCodeCamp/labels?q=scope) and few others scopes added by automated workflows. 

and so far, I change like below. Let me know your thoughts

<img width="722" height="635" alt="Image" src="https://github.com/user-attachments/assets/63db4f24-73b8-4587-ae7f-348a201620c9" />

**Comment by raisedadead** [comment]
Thanks everyone. 

I am going to go ahead and close this long standing umbrella issue. At some point I will do some additional auditing, but it seems content review of the guides will have to be an ongoing activity and doesnt need close tracking.
