### ISSUE TITLE
Branching and Migration Notice

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#16]
Hey all, 

We [announced](https://forum.freecodecamp.org/t/things-we-are-working-on-this-year/675433) that the contribute platform is going to become more than a docs website.

We are rebuilding the platform in several phases. The first phase is pure 1:1 move from the previous setup to new setup. This includes GitHub Pages → ~~Cloudflare Pages~~ Cloud; Mono-repo → dedicated repo and [docsify](https://docsify.js.org/#/) → [Astro](https://astro.build/).

This is a quick FYI of how we plan to do this:

1. The basic migration boils down to below steps:

	```[tasklist]
	### Tasks
	- [x] Moving the docs from the main repo to its own repo. You are reading this issue on the new repo!  
	- [x] Refactoring the UI by moving from docsify to Astro.
	- [x] Porting the content and making it work with Astro. For ex: docsify content uses special markdown syntax for annotations like banners, etc.
	- [ ] Following the brand design language for the styling (CSS, Imagery).
	- [x] Deploying to ~~Cloudflare pages~~ cloud via GitHub Actions, etc.
	```

2. Branches:
   - The current docsify-based website code is moved into the [`legacy`](https://github.com/freeCodeCamp/contribute/tree/legacy) branch.
   - All existing content PRs should target the said `legacy` branch to prevent any disruptions.
   - The `main` branch is the development branch for the new website and platform.
   - The `live` branch is the deployment branch. Currently points to `https://beta.contribute.freecodecamp.org`
   - The `live` branch will eventually become the deployment branch for the actual `https://contribute.freecodecamp.org` URL.

3. As a result any PRs made to the `legacy` branch will need to be created again for the `main` branch during the transition.

**Comment by raisedadead** [comment]
The `main` branch is now the primary/default development branch and the code is deployed when `main` is merged into the `live` branch.

The `legacy` branch will remain on this repo for posterity for a few weeks.
