### ISSUE TITLE
Integrate Linting and other common dev tooling

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#36]
Need to integrate tools like linters, formatter, commit hooks (husky), editorconfig etc.
```[tasklist]
### Tasks
- [x] Add a formatter – DONE: #38
- [ ] Add a linter
- [x] Add editor config - DONE: #38
- [x] Add commit hooks - DONE: #38
```

**Comment by raisedadead** [comment]
We will still need eslint.
