### ISSUE TITLE
Move over Code and Content from main repo

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/contribute#5]
```[tasklist]
### Tasks
- [ ] https://github.com/freeCodeCamp/contribute/pull/3
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/pull/53882
- [x] Copy over code and files with Git history
- [x] Remap the custom domain from the main repo
- [x] Enable GitHub pages on the Contribute repo
- [x] Clean up the main repo settings related to docs
```
